version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/app/frontend 
    command: sh -c "cd mpfar && npm run dev"
    ports:
      - "3000:3000"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    container_name: backend-flask
    volumes:
      - ./backend:/usr/src/app/backend
    command: flask run --host=0.0.0.0